### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by jarlabanke** [MobileNativeFoundation/Kronos#41]
Is possible to get an estimate of the accuracy from the sync call? E.g. based on the network latency.

**Comment by Reflejo** [comment]
Sounds like a good idea, do you want to take a stab at it?

**Comment by jarlabanke** [comment]
My solution was to calculate a delay in the "offset function" in NTPClient.swift in the same manner as the offset (but from bestResponses[i].delay instead) and return that together with the offset. That delay gives an indication of the uncertainty/accuracy of the call.
