### ISSUE TITLE
Address Sanitizer: heap-buffer-overflow

### ISSUE THREAD

**Issue by truemetal** [MobileNativeFoundation/Kronos#47]
Steps:
1. Create empty iOS single view application project
2. pod init 
3. add pod 'Kronos' to pod file 
4. pod install
5. In ViewController or app delegate `import Kronos` and `Clock.sync()` 
6. Enable address sanitizer
7. Run app and you get an issue

![screen shot 2018-11-07 at 4 27 44 pm](https://user-images.githubusercontent.com/2472186/48137144-0fab4380-e2aa-11e8-99ad-de3dca327bfc.png)

[address sanitizer log.txt](https://github.com/lyft/Kronos/files/2557664/address.sanitizer.log.txt)

[test-kronos.zip](https://github.com/lyft/Kronos/files/2557694/test-kronos.zip)

**Comment by x-du** [comment]
Have the same issue.

**Comment by liangjiapei** [comment]
Same issue here. Has anyone looked into this issue yet? I have tried both debug and release build configurations, and both of them have the same issue.

**Comment by Reflejo** [comment]
Fix here: https://github.com/lyft/Kronos/pull/56

Sorry for the wait

**Comment by keith** [comment]
Released in https://github.com/MobileNativeFoundation/Kronos/releases/tag/4.2.0
