### ISSUE TITLE
Crash in NTPPacket.swift

### ISSUE THREAD

**Issue by jarlabanke** [MobileNativeFoundation/Kronos#73]
I am getting crash reports from NTPPacket, not a lot since there are thousand of users, but 10 in the last two weeks. Sometimes the user has been running the app for an hour without problems. It is also weird that the log points to line 20, which is empty (but that could be an error in the reporting).

MAIN THREAD - CRASHED
CoreFoundation	_CFAssertMismatchedTypeID
CoreFoundation	CFRunLoopSourceInvalidate
CFNetwork		CFNetServiceBrowserStopSearch
CoreFoundation	_CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
CoreFoundation	__CFRunLoopDoSource0
CoreFoundation	__CFRunLoopDoSources0
SprintTimer		main NTPPacket.swift:20
libdyld.dylib	start

**Comment by Reflejo** [comment]
Can you send the full crash report? Can't do much with that one :) and maybe try the new master - we fished one long standing memory management issue

**Comment by jarlabanke** [comment]
Incident Identifier: d3928f1d-1348-4665-b6ca-42f9f82841e0
CrashReporter Key:   8CA75A33-98F0-42D9-A7F7-6C487EEB0818
Hardware Model:      iPhone12,1
Process:         SprintTimer [3531]
Path:            /private/var/containers/Bundle/Application/E80886DA-0417-402B-9C38-4B1D57A8ED79/SprintTimer.app/SprintTimer
Identifier:      sprintTimer
Version:         16.0.1 (160.1)
Code Type:       arm64
Parent Process:  ??? [1]

Date/Time:       2020-11-27T23:32:36.999Z
Launch Time:     2020-11-27T22:43:07Z
OS Version:      iPhone OS 14.2 (18B92)
Report Version:  104

Exception Type:  SIGTRAP
Exception Codes: TRAP_BRKPT at 0x19caf22c4
Crashed Thread:  0

Thread 0 Crashed:
0   CoreFoundation                       0x000000019caf22c4 _CFAssertMismatchedTypeID + 112
1   CoreFoundation                       0x000000019c9f8d80 CFRunLoopSourceInvalidate + 304
2   CFNetwork                            0x000000019d0d4224 CFNetServiceBrowserStopSearch + 468
3   CoreFoundation                       0x000000019c9fc76c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
4   CoreFoundation                       0x000000019c9fc668 __CFRunLoopDoSource0 + 204
5   CoreFoundation                       0x000000019c9fb960 __CFRunLoopDoSources0 + 264
6   CoreFoundation                       0x000000019c9f5a8c __CFRunLoopRun + 820
7   CoreFoundation                       0x000000019c9f521c CFRunLoopRunSpecific + 596
8   GraphicsServices                     0x00000001b3a74784 GSEventRunModal + 160
9   UIKitCore                            0x000000019f42e200 -[UIApplication _run] + 1068
10  UIKitCore                            0x000000019f433a74 UIApplicationMain + 164
11  SprintTimer                          0x0000000104336614 main (NTPPacket.swift:20)
12  libdyld.dylib                        0x000000019c6b56c0 start + 0

Thread 1:
0   libsystem_kernel.dylib               0x00000001c995b2d0 mach_msg_trap + 8
1   CoreFoundation                       0x000000019c9fbc30 __CFRunLoopServiceMachPort + 376
2   CoreFoundation                       0x000000019c9f5c14 __CFRunLoopRun + 1212
3   CoreFoundation                       0x000000019c9f521c CFRunLoopRunSpecific + 596
4   Foundation                           0x000000019dca1df0 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 228
5   Foundation                           0x000000019dca1cbc -[NSRunLoop(NSRunLoop) runUntilDate:] + 88
6   UIKitCore                            0x000000019f4e1fe4 -[UIEventFetcher threadMain] + 512
7   Foundation                           0x000000019de13a34 __NSThread__start__ + 860
8   libsystem_pthread.dylib              0x00000001e5e96b40 _pthread_start + 316
9   libsystem_pthread.dylib              0x00000001e5e9f768 thread_start + 4

Thread 2:
0   SprintTimer                          0x000000010444cb30 mach_exception_callback + 176
1   SprintTimer                          0x00000001044597a4 exception_server_thread + 908
2   libsystem_pthread.dylib              0x00000001e5e96b40 _pthread_start + 316
3   libsystem_pthread.dylib              0x00000001e5e9f768 thread_start + 4

Thread 3:
0   libsystem_kernel.dylib               0x00000001c9958234 voucher_mach_msg_revert + 8
1   CoreFoundation                       0x000000019c9fbca4 __CFRunLoopServiceMachPort + 492
2   CoreFoundation                       0x000000019c9f5c14 __CFRunLoopRun + 1212
3   CoreFoundation                       0x000000019c9f521c CFRunLoopRunSpecific + 596
4   AudioSession                         0x00000001a44570c4 0x1a444a000 + 8085814557978710212
5   AudioSession                         0x00000001a445925c 0x1a444a000 + 6853584729904575068
6   libsystem_pthread.dylib              0x00000001e5e96b40 _pthread_start + 316
7   libsystem_pthread.dylib              0x00000001e5e9f768 thread_start + 4

Thread 4:
0   libsystem_kernel.dylib               0x00000001c995b2d0 mach_msg_trap + 8
1   CoreFoundation                       0x000000019c9fbc30 __CFRunLoopServiceMachPort + 376
2   CoreFoundation                       0x000000019c9f5c14 __CFRunLoopRun + 1212
3   CoreFoundation                       0x000000019c9f521c CFRunLoopRunSpecific + 596
4   CFNetwork                            0x000000019d2c8410 _CFURLStorageSessionCopyCache + 64448
5   Foundation                           0x000000019de13a34 __NSThread__start__ + 860
6   libsystem_pthread.dylib              0x00000001e5e96b40 _pthread_start + 316
7   libsystem_pthread.dylib              0x00000001e5e9f768 thread_start + 4

Thread 5:
0   libsystem_kernel.dylib               0x00000001c997f70c __select + 8
1   libsystem_pthread.dylib              0x00000001e5e96b40 _pthread_start + 316
2   libsystem_pthread.dylib              0x00000001e5e9f768 thread_start + 4

Thread 6:
0   libsystem_kernel.dylib               0x00000001c997f1ac __psynch_cvwait + 8
1   libc++.1.dylib                       0x00000001b1077328 0x1b106a000 + 3412174907616842536
2   JavaScriptCore                       0x00000001a6cb5c04 0x1a5df9000 + 8292298443643931652
3   JavaScriptCore                       0x00000001a6cba2d0 0x1a5df9000 + -2664302491550870832
4   JavaScriptCore                       0x00000001a6cb9edc 0x1a5df9000 + 6156751643630898908
5   JavaScriptCore                       0x00000001a6cbb3f4 0x1a5df9000 + 1524462976322249716
6   libsystem_pthread.dylib              0x00000001e5e96b40 _pthread_start + 316
7   libsystem_pthread.dylib              0x00000001e5e9f768 thread_start + 4

Thread 7:
0   libsystem_kernel.dylib               0x00000001c995b2d0 mach_msg_trap + 8
1   CoreFoundation                       0x000000019c9fbc30 __CFRunLoopServiceMachPort + 376
2   CoreFoundation                       0x000000019c9f5c14 __CFRunLoopRun + 1212
3   CoreFoundation                       0x000000019c9f521c CFRunLoopRunSpecific + 596
4   WebCore                              0x00000001aa07c87c 0x1a94ad000 + -7345099412856833924
5   libsystem_pthread.dylib              0x00000001e5e96b40 _pthread_start + 316
6   libsystem_pthread.dylib              0x00000001e5e9f768 thread_start + 4

Thread 8:
0   libsystem_kernel.dylib               0x00000001c995b2d0 mach_msg_trap + 8
1   CoreFoundation                       0x000000019c9fbc30 __CFRunLoopServiceMachPort + 376
2   CoreFoundation                       0x000000019c9f5c14 __CFRunLoopRun + 1212
3   CoreFoundation                       0x000000019c9f521c CFRunLoopRunSpecific + 596
4   CoreFoundation                       0x000000019c9f62fc CFRunLoopRun + 60
5   CoreMotion                           0x00000001a79ef180 CLClientCreateIso6709Notation + 179036
6   libsystem_pthread.dylib              0x00000001e5e96b40 _pthread_start + 316
7   libsystem_pthread.dylib              0x00000001e5e9f768 thread_start + 4

Thread 9:
0   libsystem_kernel.dylib               0x00000001c995b30c semaphore_wait_trap + 8
1   caulk                                0x00000001e10910ac 0x1e1084000 + -6094551171320459092
2   caulk                                0x00000001e1096398 0x1e1084000 + -6967302269762985064
3   caulk                                0x00000001e109657c 0x1e1084000 + 7165621731820905852
4   libsystem_pthread.dylib              0x00000001e5e96b40 _pthread_start + 316
5   libsystem_pthread.dylib              0x00000001e5e9f768 thread_start + 4

Thread 10:
0   libsystem_kernel.dylib               0x00000001c995b2d0 mach_msg_trap + 8
1   libEmbeddedSystemAUs.dylib           0x00000001cdb0f768 0x1cda79000 + -7098623540537497752
2   libsystem_pthread.dylib              0x00000001e5e96b40 _pthread_start + 316
3   libsystem_pthread.dylib              0x00000001e5e9f768 thread_start + 4

Thread 11:
0   libsystem_kernel.dylib               0x00000001c997f70c __select + 8
1   libsystem_pthread.dylib              0x00000001e5e96b40 _pthread_start + 316
2   libsystem_pthread.dylib              0x00000001e5e9f768 thread_start + 4

Thread 12:
0   libsystem_kernel.dylib               0x00000001c997f70c __select + 8
1   libsystem_pthread.dylib              0x00000001e5e96b40 _pthread_start + 316
2   libsystem_pthread.dylib              0x00000001e5e9f768 thread_start + 4

Thread 13:
0   libsystem_kernel.dylib               0x00000001c997f1ac __psynch_cvwait + 8
1   MultipeerConnectivity                0x00000001cf53d8f4 0x1cf50d000 + -2139373100477511436
2   libsystem_pthread.dylib              0x00000001e5e96b40 _pthread_start + 316
3   libsystem_pthread.dylib              0x00000001e5e9f768 thread_start + 4

Thread 14:
0   libsystem_kernel.dylib               0x00000001c995b2d0 mach_msg_trap + 8
1   CoreFoundation                       0x000000019c9fbc30 __CFRunLoopServiceMachPort + 376
2   CoreFoundation                       0x000000019c9f5c14 __CFRunLoopRun + 1212
3   CoreFoundation                       0x000000019c9f521c CFRunLoopRunSpecific + 596
4   CoreFoundation                       0x000000019ca18f38 _legacyStreamRunLoop_workThread + 276
5   libsystem_pthread.dylib              0x00000001e5e96b40 _pthread_start + 316
6   libsystem_pthread.dylib              0x00000001e5e9f768 thread_start + 4

Thread 15:
0   libsystem_kernel.dylib               0x00000001c9980184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001e5e9f75c start_wqthread + 4

Thread 16:
0   libsystem_kernel.dylib               0x00000001c9980184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001e5e9f75c start_wqthread + 4

Thread 17:
0   libsystem_kernel.dylib               0x00000001c9980184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001e5e9f75c start_wqthread + 4

Thread 18:
0   libsystem_kernel.dylib               0x00000001c9980184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001e5e9f75c start_wqthread + 4

Thread 19:
0   libsystem_pthread.dylib              0x00000001e5e9f754 start_wqthread + 0

Thread 20:
0   libsystem_kernel.dylib               0x00000001c997f1ac __psynch_cvwait + 8
1   Foundation                           0x000000019dd233e4 -[NSOperation waitUntilFinished] + 580
2   Foundation                           0x000000019ddcd594 __NSOPERATIONQUEUE_IS_WAITING_ON_AN_OPERATION__ + 20
3   Foundation                           0x000000019dd0a2cc -[NSOperationQueue addOperations:waitUntilFinished:] + 168
4   WatchConnectivity                    0x00000001d0fb06b0 0x1d0f92000 + -8066629729341282640
5   WatchConnectivity                    0x00000001d0fbb50c 0x1d0f92000 + -8907088721031817972
6   WatchConnectivity                    0x00000001d0fa9c40 0x1d0f92000 + -4727960472576230336
7   Foundation                           0x000000019ddcc850 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 20
8   Foundation                           0x000000019dcb9740 -[NSBlockOperation main] + 100
9   Foundation                           0x000000019ddceca4 __NSOPERATION_IS_INVOKING_MAIN__ + 20
10  Foundation                           0x000000019dcb93c8 -[NSOperation start] + 804
11  Foundation                           0x000000019ddcf74c __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 20
12  Foundation                           0x000000019ddcf1d4 __NSOQSchedule_f + 180
13  libdispatch.dylib                    0x000000019c67324c _dispatch_call_block_and_release + 28
14  libdispatch.dylib                    0x000000019c674db0 _dispatch_client_callout + 16
15  libdispatch.dylib                    0x000000019c67812c _dispatch_continuation_pop + 412
16  libdispatch.dylib                    0x000000019c677854 _dispatch_async_redirect_invoke + 588
17  libdispatch.dylib                    0x000000019c68593c _dispatch_root_queue_drain + 352
18  libdispatch.dylib                    0x000000019c686120 _dispatch_worker_thread2 + 112
19  libsystem_pthread.dylib              0x00000001e5e987c8 _pthread_wqthread + 212
20  libsystem_pthread.dylib              0x00000001e5e9f75c start_wqthread + 4

Thread 21:
0   libsystem_kernel.dylib               0x00000001c9980184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001e5e9f75c start_wqthread + 4

Thread 22:
0   libsystem_pthread.dylib              0x00000001e5e9f754 start_wqthread + 0

Thread 23:
0   libsystem_kernel.dylib               0x00000001c995b2d0 mach_msg_trap + 8
1   libdispatch.dylib                    0x000000019c68d888 _dispatch_mach_send_and_wait_for_reply + 524
2   libdispatch.dylib                    0x000000019c68dc24 dispatch_mach_send_with_result_and_wait_for_reply + 52
3   libxpc.dylib                         0x00000001e5ebde68 0x1e5eb0000 + 667800481757716072
4   CoreMedia                            0x00000001a58bb7bc 0x1a57e1000 + -3574103833329162308
5   CoreMedia                            0x00000001a58bb92c 0x1a57e1000 + -4296198199266399956
6   MediaToolbox                         0x00000001a523e620 0x1a500b000 + -5228364707049294304
7   MediaToolbox                         0x00000001a524a4a0 0x1a500b000 + -1131938424700013408
8   libdispatch.dylib                    0x000000019c674db0 _dispatch_client_callout + 16
9   libdispatch.dylib                    0x000000019c683428 _dispatch_lane_barrier_sync_invoke_and_complete + 56
10  MediaToolbox                         0x00000001a524a270 0x1a500b000 + -771670245719674256
11  MediaToolbox                         0x00000001a523e9f8 0x1a500b000 + -7911618381031982600
12  CoreFoundation                       0x000000019c9dd9a0 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 24
13  CoreFoundation                       0x000000019c9dd948 ___CFXRegistrationPost_block_invoke + 48
14  CoreFoundation                       0x000000019c9dceb0 _CFXRegistrationPost + 436
15  CoreFoundation                       0x000000019c9dc870 _CFXNotificationPost + 712
16  CoreFoundation                       0x000000019c9dd4a8 CFNotificationCenterPostNotificationWithOptions + 132
17  CoreMedia                            0x00000001a57fe8fc 0x1a57e1000 + 8534286109495122172
18  libdispatch.dylib                    0x000000019c67324c _dispatch_call_block_and_release + 28
19  libdispatch.dylib                    0x000000019c674db0 _dispatch_client_callout + 16
20  libdispatch.dylib                    0x000000019c67c10c _dispatch_lane_serial_drain + 576
21  libdispatch.dylib                    0x000000019c67cc5c _dispatch_lane_invoke + 404
22  libdispatch.dylib                    0x000000019c686d78 _dispatch_workloop_worker_thread + 704
23  libsystem_pthread.dylib              0x00000001e5e98804 _pthread_wqthread + 272
24  libsystem_pthread.dylib              0x00000001e5e9f75c start_wqthread + 4

Thread 24:
0   libsystem_kernel.dylib               0x00000001c995b2d0 mach_msg_trap + 8
1   libdispatch.dylib                    0x000000019c68d888 _dispatch_mach_send_and_wait_for_reply + 524
2   libdispatch.dylib                    0x000000019c68dc24 dispatch_mach_send_with_result_and_wait_for_reply + 52
3   libxpc.dylib                         0x00000001e5ebde68 0x1e5eb0000 + -5597462514158739864
4   CoreMedia                            0x00000001a58bb7bc 0x1a57e1000 + -5257772794803017796
5   CoreMedia                            0x00000001a58bb92c 0x1a57e1000 + 4686058634198493484
6   MediaToolbox                         0x00000001a523e620 0x1a500b000 + 532311512159827488
7   MediaToolbox                         0x00000001a524a4a0 0x1a500b000 + -3659464968305904480
8   libdispatch.dylib                    0x000000019c674db0 _dispatch_client_callout + 16
9   libdispatch.dylib                    0x000000019c683428 _dispatch_lane_barrier_sync_invoke_and_complete + 56
10  MediaToolbox                         0x00000001a524a270 0x1a500b000 + -5748503525975657872
11  MediaToolbox                         0x00000001a523e9f8 0x1a500b000 + -2419326353093215752
12  CoreFoundation                       0x000000019c9dd9a0 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 24
13  CoreFoundation                       0x000000019c9dd948 ___CFXRegistrationPost_block_invoke + 48
14  CoreFoundation                       0x000000019c9dceb0 _CFXRegistrationPost + 436
15  CoreFoundation                       0x000000019c9dc870 _CFXNotificationPost + 712
16  CoreFoundation                       0x000000019c9dd4a8 CFNotificationCenterPostNotificationWithOptions + 132
17  CoreMedia                            0x00000001a57fe8fc 0x1a57e1000 + -426693524704864004
18  libdispatch.dylib                    0x000000019c67324c _dispatch_call_block_and_release + 28
19  libdispatch.dylib                    0x000000019c674db0 _dispatch_client_callout + 16
20  libdispatch.dylib                    0x000000019c67c10c _dispatch_lane_serial_drain + 576
21  libdispatch.dylib                    0x000000019c67cc5c _dispatch_lane_invoke + 404
22  libdispatch.dylib                    0x000000019c686d78 _dispatch_workloop_worker_thread + 704
23  libsystem_pthread.dylib              0x00000001e5e98804 _pthread_wqthread + 272
24  libsystem_pthread.dylib              0x00000001e5e9f75c start_wqthread + 4

Thread 25:
0   libsystem_kernel.dylib               0x00000001c995b2d0 mach_msg_trap + 8
1   libdispatch.dylib                    0x000000019c68d888 _dispatch_mach_send_and_wait_for_reply + 524
2   libdispatch.dylib                    0x000000019c68dc24 dispatch_mach_send_with_result_and_wait_for_reply + 52
3   libxpc.dylib                         0x00000001e5ebde68 0x1e5eb0000 + 9176902277418507880
4   CoreMedia                            0x00000001a58bb7bc 0x1a57e1000 + 2964306438229174204
5   CoreMedia                            0x00000001a58bb92c 0x1a57e1000 + -8468231848943834836
6   MediaToolbox                         0x00000001a523e620 0x1a500b000 + -4104949696485444064
7   MediaToolbox                         0x00000001a513b5a4 0x1a500b000 + -7028081623277828700
8   MediaToolbox                         0x00000001a513e3bc 0x1a500b000 + -7907571078731189316
9   libdispatch.dylib                    0x000000019c674db0 _dispatch_client_callout + 16
10  libdispatch.dylib                    0x000000019c67c10c _dispatch_lane_serial_drain + 576
11  libdispatch.dylib                    0x000000019c67cc5c _dispatch_lane_invoke + 404
12  libdispatch.dylib                    0x000000019c686d78 _dispatch_workloop_worker_thread + 704
13  libsystem_pthread.dylib              0x00000001e5e98804 _pthread_wqthread + 272
14  libsystem_pthread.dylib              0x00000001e5e9f75c start_wqthread + 4

Thread 26:
0   libsystem_kernel.dylib               0x00000001c9980184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001e5e9f75c start_wqthread + 4

Thread 27:
0   libsystem_kernel.dylib               0x00000001c995b2d0 mach_msg_trap + 8
1   libdispatch.dylib                    0x000000019c68d888 _dispatch_mach_send_and_wait_for_reply + 524
2   libdispatch.dylib                    0x000000019c68dc24 dispatch_mach_send_with_result_and_wait_for_reply + 52
3   libxpc.dylib                         0x00000001e5ebde68 0x1e5eb0000 + -6965418806344622488
4   CoreMedia                            0x00000001a58bb7bc 0x1a57e1000 + -8619767091239737412
5   CoreMedia                            0x00000001a58bb92c 0x1a57e1000 + 1760429716500490540
6   MediaToolbox                         0x00000001a523e620 0x1a500b000 + 9104103612545709600
7   MediaToolbox                         0x00000001a513b5a4 0x1a500b000 + -1551999695267363420
8   MediaToolbox                         0x00000001a513e3bc 0x1a500b000 + 4399393962605097916
9   libdispatch.dylib                    0x000000019c674db0 _dispatch_client_callout + 16
10  libdispatch.dylib                    0x000000019c67c10c _dispatch_lane_serial_drain + 576
11  libdispatch.dylib                    0x000000019c67cc5c _dispatch_lane_invoke + 404
12  libdispatch.dylib                    0x000000019c686d78 _dispatch_workloop_worker_thread + 704
13  libsystem_pthread.dylib              0x00000001e5e98804 _pthread_wqthread + 272
14  libsystem_pthread.dylib              0x00000001e5e9f75c start_wqthread + 4

Thread 28:
0   libsystem_kernel.dylib               0x00000001c9980184 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001e5e9f75c start_wqthread + 4

Thread 29:
0   ???                                  0x0000000000000000 0x0 + 0

Thread 0 crashed with arm64 Thread State:
   x21: 0x000000019cccad30     x2: 0x0000000000000000    x16: 0x00000001abe1ed54     x3: 0x000000016bb228f0
   x22: 0x000000019ccd3068     x4: 0x000000016bb22320    x17: 0x00000001f8a52448   cpsr: 0x0000000060000000
    x5: 0x000000016bb22880    x23: 0x00000001fc200000     x6: 0x0000000000000029    x18: 0x000000010a0f98cc
   x10: 0x0000000000000001     lr: 0x000000019caf22bc     x7: 0x00000002831a8270    x24: 0x00000001f24ab000
   x11: 0x0000000000000005     x8: 0x00000001f24ab000    x19: 0x000000016bb228a1    x25: 0x0000000000000000
    x9: 0x00000004e234004b    x12: 0x0000000000000000     fp: 0x000000016bb229d0    x26: 0x000000016bb22c20
   x13: 0x0000000000000000     pc: 0x000000019caf22c4    x27: 0x00000001fc200000    x14: 0x0000000000000010
   x20: 0x000000000000002e     x0: 0x000000000000004f     sp: 0x000000016bb22880    x28: 0x00000001f24ab000
   x15: 0x0000000000000000     x1: 0x000000019ccd3a8d

Binary Images:
0x00000001042dc000 -        0x00000001044cbfff +SprintTimer arm64  <6cb623d09b1f36a381073bcdb507b6d3> /private/var/containers/Bundle/Application/E80886DA-0417-402B-9C38-4B1D57A8ED79/SprintTimer.app/SprintTimer
0x000000019c671000 -        0x000000019c6b3fff  libdispatch.dylib arm64  <3277bf1eb99436099b30e0186bbf3c25> /usr/lib/system/libdispatch.dylib
0x000000019c6b4000 -        0x000000019c6eefff  libdyld.dylib arm64  <ba60cb9e95c53646beedd313e15586cf> /usr/lib/system/libdyld.dylib
0x000000019c95b000 -        0x000000019cd14fff  CoreFoundation arm64  <af3f8e01c1303464ad40c5532d273483> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
0x000000019d07c000 -        0x000000019d513fff  CFNetwork arm64  <f8c7b81649ab39479309b8975a7ccea0> /System/Library/Frameworks/CFNetwork.framework/CFNetwork
0x000000019dc99000 -        0x000000019df54fff  Foundation arm64  <5c24ee4a344736bd99106f4d9616d692> /System/Library/Frameworks/Foundation.framework/Foundation
0x000000019e867000 -        0x000000019fd12fff  UIKitCore arm64  <05147936b8753ef394db9c8869bb0e34> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
0x00000001a444a000 -        0x00000001a4462fff  AudioSession arm64  <06325a11a821335292c6284edabfbc15> /System/Library/PrivateFrameworks/AudioSession.framework/AudioSession
0x00000001a500b000 -        0x00000001a57e0fff  MediaToolbox arm64  <db06c5fe5a6a304aac1deb7df01b80e4> /System/Library/Frameworks/MediaToolbox.framework/MediaToolbox
0x00000001a57e1000 -        0x00000001a58e1fff  CoreMedia arm64  <c8985fcd606d3540af2ccf5832a16396> /System/Library/Frameworks/CoreMedia.framework/CoreMedia
0x00000001a5df9000 -        0x00000001a6da9fff  JavaScriptCore arm64  <effee71cb880376fb623bb993b9fa656> /System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore
0x00000001a78a9000 -        0x00000001a7b0efff  CoreMotion arm64  <7a5d78df574b3eeab03e93af4a2c445c> /System/Library/Frameworks/CoreMotion.framework/CoreMotion
0x00000001a94ad000 -        0x00000001ab911fff  WebCore arm64  <9fb90b9144ab3e6999ce546c8c889e76> /System/Library/PrivateFrameworks/WebCore.framework/WebCore
0x00000001abe0c000 -        0x00000001abe2ffff  libsystem_malloc.dylib arm64  <cfae13f05b0a3ce5b3d2c2f7276c1fe1> /usr/lib/system/libsystem_malloc.dylib
0x00000001b106a000 -        0x00000001b10c8fff  libc++.1.dylib arm64  <540a1413a396391a83dbfe9ee2bc1413> /usr/lib/libc++.1.dylib
0x00000001b3a71000 -        0x00000001b3a79fff  GraphicsServices arm64  <d365efcf659c3292b2035692107edd1d> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
0x00000001c9957000 -        0x00000001c9988fff  libsystem_kernel.dylib arm64  <03a89b86f9473933b6a1edb0c6a2055e> /usr/lib/system/libsystem_kernel.dylib
0x00000001cda79000 -        0x00000001cdb8dfff  libEmbeddedSystemAUs.dylib arm64  <e64b3cfd138033a0bd3138c9e4f684f5> /System/Library/Frameworks/AudioToolbox.framework/libEmbeddedSystemAUs.dylib
0x00000001cf50d000 -        0x00000001cf552fff  MultipeerConnectivity arm64  <ec3e172f1ec231ce9f3192c0646679b8> /System/Library/Frameworks/MultipeerConnectivity.framework/MultipeerConnectivity
0x00000001d0f92000 -        0x00000001d0fcefff  WatchConnectivity arm64  <b537f2c757da3e158eed815192c17bb4> /System/Library/Frameworks/WatchConnectivity.framework/WatchConnectivity
0x00000001e1084000 -        0x00000001e10a3fff  caulk arm64  <c825451a58ec3b2a9db761cea4058cea> /System/Library/PrivateFrameworks/caulk.framework/caulk
0x00000001e5e95000 -        0x00000001e5ea0fff  libsystem_pthread.dylib arm64  <677a4a3539f3303e8c653fa891a75caf> /usr/lib/system/libsystem_pthread.dylib
0x00000001e5eb0000 -        0x00000001e5ee6fff  libxpc.dylib arm64  <71a903b4e73136b6bfdaba9e03b53e8c> /usr/lib/system/libxpc.dylib

**Comment by Reflejo** [comment]
Have you tried the new master at that point? Do you still see this issue? I'll re-open if you do

**Comment by shuangwei-Ye** [comment]
> I am getting crash reports from NTPPacket, not a lot since there are thousand of users, but 10 in the last two weeks. Sometimes the user has been running the app for an hour without problems. It is also weird that the log points to line 20, which is empty (but that could be an error in the reporting).
> 
> MAIN THREAD - CRASHED
> CoreFoundation _CFAssertMismatchedTypeID CoreFoundation CFRunLoopSourceInvalidate CFNetwork CFNetServiceBrowserStopSearch CoreFoundation _CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
> CoreFoundation __CFRunLoopDoSource0
> CoreFoundation __CFRunLoopDoSources0
> SprintTimer main NTPPacket.swift:20
> libdyld.dylib start

----------------------------
Do you still see this issue?  i have this issue
