### ISSUE TITLE
Authorisation asked for local network on iOS 14 on cellular network

### ISSUE THREAD

**Issue by ben-j69** [MobileNativeFoundation/Kronos#94]
Hello,

if the lib is inclued in an app running on iOS 14 an authorisation is asked at launch in a system popup : 

> "NAME_OF_YOUR_APP" would like to find and connect to devices on your local network.
> This app will be able to discover and connect to devices on the networks you use.
> Don't allow - OK

This does not appear on Wi-Fi, it is displayed only if the phone is on cellular network like 4G.

This is triggered by `Clock.sync()`

Why Kronos wants to use local network ? How to avoid this popup in any case ?

Thanks

**Comment by ncreated** [comment]
👋 As a follow up from corresponding issue in Datadog iOS SDK, we managed to collect Kronos telemetry which shows [an evidence of resolving NTP pool to a private / local IP](https://github.com/DataDog/dd-sdk-ios/issues/647#issuecomment-1108489161) in some (unknown) circumstances. As a fix, we're going to apply private IP filtering in https://github.com/DataDog/dd-sdk-ios/pull/830 on our side. We believe this could be a desired change to Kronos lib as well.

**Comment by jeannustre** [comment]
Thanks @ncreated !

I have opened PR https://github.com/MobileNativeFoundation/Kronos/pull/100 which includes DataDog's changes. Let me know if there's any issue with it.
